export { DashboardHeaderWidget } from './widgets/DashboardHeaderWidget';
export { ProgressHeroWidget } from './widgets/ProgressHeroWidget';
export { CurrentMealWidget as ActionableCurrentMealWidget, CurrentMealWidget } from './widgets/CurrentMealWidget';
export { HealixAICardWidget as ContextualAICoachWidget, HealixAICardWidget } from './widgets/HealixAICardWidget';
export { QuickActionsWidget } from './widgets/QuickActionsWidget';
export { IndicatorsWidget as TodayIndicatorsWidget, IndicatorsWidget } from './widgets/IndicatorsWidget';
export { WaterWidget as WaterTrackerWidget, WaterWidget } from './widgets/WaterWidget';
export { WorkoutWidget as WorkoutSectionWidget, WorkoutWidget } from './widgets/WorkoutWidget';
export { MovementWidget as DailyActivityWidget, MovementWidget } from './widgets/MovementWidget';
export { TimelineWidget as LiveTimelineWidget, TimelineWidget } from './widgets/TimelineWidget';
export { MoreBottomSheetModal } from './widgets/MoreBottomSheetModal';
