import { StyleSheet } from 'react-native';

export const medicalStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F9F6F0' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  scrollContent: { padding: 20 },
  
  header: { padding: 20, paddingBottom: 10, alignItems: 'flex-start' },
  title: { fontSize: 26, fontWeight: '900', color: '#2A4B46', marginBottom: 5 },
  subtitle: { fontSize: 14, color: '#6B7280', fontWeight: 'bold' },

  tabScrollContainer: { paddingHorizontal: 15, paddingBottom: 15, flexDirection: 'row', gap: 10 },
  tabBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F3F4F6', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, gap: 6 },
  tabBtnActive: { backgroundColor: '#FFF', elevation: 2, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 4 },
  tabText: { fontSize: 14, fontWeight: 'bold', color: '#9CA3AF' },
  tabTextActive: { color: '#2A4B46' },

  fadeContainer: { flex: 1 },

  // Profile Cards
  profileCard: { backgroundColor: '#FFF', borderRadius: 25, padding: 20, elevation: 1 },
  profileHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#F3F4F6', paddingBottom: 15, marginBottom: 15 },
  profileTitle: { fontSize: 18, fontWeight: 'bold', color: '#1F2937' },
  editBtnSmall: { backgroundColor: '#2A4B46', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, gap: 5 },
  editBtnText: { color: '#FFF', fontSize: 12, fontWeight: 'bold' },
  profileBody: { gap: 15 },
  dataGroup: { alignItems: 'flex-start' },
  dataLabel: { fontSize: 12, color: '#9CA3AF', fontWeight: 'bold', marginBottom: 5 },
  dataValueBox: { backgroundColor: '#F9F6F0', width: '100%', padding: 12, borderRadius: 10, textAlign: 'left', fontWeight: 'bold', color: '#1F2937' },
  dataValueRed: { color: '#EF4444', fontWeight: 'bold' },
  dataValueGreen: { color: '#10B981', fontWeight: 'bold' },

  // Chips & Groups
  chipsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chipRed: { backgroundColor: '#FEE2E2', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  chipRedText: { color: '#EF4444', fontSize: 12, fontWeight: 'bold' },
  chipGreen: { backgroundColor: '#D1FAE5', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  chipGreenText: { color: '#10B981', fontSize: 12, fontWeight: 'bold' },
  
  chipSelect: { backgroundColor: '#F3F4F6', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 10, borderWidth: 1, borderColor: '#E5E7EB' },
  chipSelectActive: { backgroundColor: '#E8F3F1', borderColor: '#2A4B46' },
  chipSelectActiveRed: { backgroundColor: '#FEE2E2', borderColor: '#EF4444' },
  chipSelectText: { color: '#6B7280', fontWeight: 'bold', fontSize: 13 },
  chipSelectTextActive: { color: '#2A4B46' },
  chipSelectTextActiveRed: { color: '#EF4444' },

  radioGroup: { flexDirection: 'row', backgroundColor: '#F3F4F6', borderRadius: 12, padding: 4 },
  radioBtn: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
  radioBtnActive: { backgroundColor: '#FFF', elevation: 1 },
  radioText: { color: '#9CA3AF', fontWeight: 'bold' },
  radioTextActive: { color: '#1F2937' },

  // Toggle (Eating Habits)
  toggleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#F9F6F0', padding: 12, borderRadius: 12, marginBottom: 8 },
  toggleText: { fontSize: 14, fontWeight: 'bold', color: '#1F2937' },
  toggleBtn: { width: 44, height: 24, backgroundColor: '#D1D5DB', borderRadius: 12, justifyContent: 'center', paddingHorizontal: 2 },
  toggleBtnActive: { backgroundColor: '#10B981' },
  toggleDot: { width: 20, height: 20, backgroundColor: '#FFF', borderRadius: 10 },
  toggleDotActive: { transform: [{ translateX: 20 }] },

  inputLong: { backgroundColor: '#F3F4F6', height: 45, borderRadius: 12, textAlign: 'left', fontSize: 14, fontWeight: 'bold', paddingHorizontal: 15 },
  inputArea: { backgroundColor: '#F3F4F6', height: 80, borderRadius: 12, textAlign: 'left', fontSize: 14, fontWeight: 'bold', paddingHorizontal: 15, paddingTop: 10 },

  // InBody & Docs Styles
  lastRecordHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10, paddingHorizontal: 5 },
  lastRecordTitle: { fontSize: 16, fontWeight: 'bold', color: '#1F2937' },
  lastRecordDate: { fontSize: 13, color: '#9CA3AF', fontWeight: 'bold', backgroundColor: '#F3F4F6', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  statsGrid: { flexDirection: 'row', gap: 10, marginBottom: 15 },
  statCard: { flex: 1, backgroundColor: '#FFF', padding: 15, borderRadius: 20, alignItems: 'center', borderWidth: 2, elevation: 1 },
  statLabel: { fontSize: 11, color: '#6B7280', fontWeight: 'bold', marginBottom: 5 },
  statValue: { fontSize: 20, fontWeight: '900', color: '#1F2937' },
  statUnit: { fontSize: 10, color: '#9CA3AF', fontWeight: 'normal' },
  emptyAlert: { backgroundColor: '#FFF7ED', padding: 20, borderRadius: 20, borderWidth: 1, borderColor: '#FFEDD5', marginBottom: 20 },
  emptyAlertText: { textAlign: 'center', color: '#F97316', fontWeight: 'bold', fontSize: 14 },
  chartContainer: { backgroundColor: '#FFF', padding: 15, borderRadius: 25, marginBottom: 20, elevation: 1, alignItems: 'center' },
  chartTitle: { fontSize: 16, fontWeight: 'bold', color: '#2A4B46', marginBottom: 15, alignSelf: 'flex-start' },
  actionRow: { flexDirection: 'row', gap: 15, marginBottom: 20 },
  actionBtn: { flex: 1, backgroundColor: '#FFF', padding: 20, borderRadius: 20, alignItems: 'center', borderWidth: 2, borderColor: '#F3F4F6', borderStyle: 'dashed' },
  actionBtnText: { marginTop: 10, fontSize: 14, fontWeight: 'bold', color: '#6B7280', textAlign: 'center' },
  formContainer: { backgroundColor: '#FFF', padding: 20, borderRadius: 25, elevation: 5, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 10, marginBottom: 20 },
  formHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  formTitle: { fontSize: 18, fontWeight: 'bold', color: '#1F2937' },
  aiSummaryBox: { backgroundColor: '#EFF6FF', padding: 15, borderRadius: 15, marginBottom: 15, borderWidth: 1, borderColor: '#DBEAFE' },
  aiSummaryTitle: { color: '#1E40AF', fontWeight: 'bold', fontSize: 13, marginBottom: 5, textAlign: 'left' },
  aiSummaryText: { color: '#1D4ED8', fontSize: 13, textAlign: 'left', lineHeight: 22 },
  inputRow: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  inputWrap: { flex: 1 },
  inputLabel: { fontSize: 12, color: '#6B7280', textAlign: 'left', marginBottom: 5, fontWeight: 'bold' },
  input: { backgroundColor: '#F3F4F6', height: 45, borderRadius: 12, textAlign: 'center', fontSize: 16, fontWeight: 'bold' },
  saveBtn: { backgroundColor: '#2A4B46', height: 50, borderRadius: 15, justifyContent: 'center', alignItems: 'center' },
  saveBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
  historySection: { marginTop: 10 },
  historySectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#2A4B46', textAlign: 'left', marginBottom: 15 },
  historyCard: { flexDirection: 'row', backgroundColor: '#FFF', padding: 15, borderRadius: 20, marginBottom: 12, borderWidth: 1, borderColor: '#F3F4F6', alignItems: 'center', elevation: 1, gap: 15 },
  historyDateBox: { width: 60, height: 60, backgroundColor: '#F9F6F0', borderRadius: 15, justifyContent: 'center', alignItems: 'center' },
  historyDay: { fontSize: 20, fontWeight: '900', color: '#2A4B46' },
  historyMonth: { fontSize: 11, fontWeight: 'bold', color: '#6B7280' },
  historyDetails: { flex: 1, alignItems: 'flex-start' },
  historyRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
  historyWeight: { fontSize: 17, fontWeight: '900', color: '#1F2937' },
  historyBadge: { fontSize: 11, fontWeight: 'bold', color: '#6B7280', backgroundColor: '#F3F4F6', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6 },
  historySummary: { fontSize: 12, color: '#9CA3AF', textAlign: 'left', lineHeight: 18 },
  uploadDocBtn: { backgroundColor: '#F3F4F6', borderWidth: 2, borderColor: '#E5E7EB', borderStyle: 'dashed', borderRadius: 30, padding: 30, alignItems: 'center', marginBottom: 25 },
  uploadDocTitle: { fontSize: 18, fontWeight: 'bold', color: '#1F2937', marginTop: 15 },
  uploadDocSub: { fontSize: 13, color: '#6B7280', marginTop: 5 },
  docsList: { gap: 12 },
  emptyText: { textAlign: 'center', color: '#9CA3AF', marginTop: 20, fontWeight: 'bold' },
  docCard: { flexDirection: 'row', backgroundColor: '#FFF', padding: 15, borderRadius: 20, alignItems: 'center', elevation: 1, borderWidth: 1, borderColor: '#F3F4F6' },
  viewDocBtn: { backgroundColor: '#F3F4F6', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 10 },
  viewDocBtnText: { color: '#2A4B46', fontWeight: 'bold', fontSize: 12 },
  docInfo: { flex: 1, alignItems: 'flex-start', paddingHorizontal: 15 },
  docName: { fontSize: 14, fontWeight: 'bold', color: '#1F2937', textAlign: 'left' },
  docDate: { fontSize: 11, color: '#9CA3AF', marginTop: 3 },
  docIconBox: { width: 45, height: 45, backgroundColor: '#EFF6FF', borderRadius: 15, justifyContent: 'center', alignItems: 'center' }
});
